#!/usr/bin/python3.9
import functions
import argparse

def main():
    parser = argparse.ArgumentParser(description="rename tv episodes")
    parser.add_argument("name", help="""the name that each episode will 
                                be renamed to with the corresponding episode
                                and season numbers"""
    )
    parser.add_argument("--season", type=int, metavar="s", help="the season to be added")
    args = parser.parse_args()

    if(args.season): 
        functions.rename_season(args.name, args.season)
    else: 
        functions.rename(args.name)

if __name__ == "__main__":
    main()
