#!/usr/bin/python3.8
import functions
import sys

def main():
    try:
        desired_name = sys.argv[1]
        functions.rename(desired_name)
    except:
        print("Please enter a second argument for the name!")
        sys.exit()


if __name__ == "__main__":
    main()
